apiVersion: batch/v1
kind: CronJob
metadata:
  name: log-cleaner-cron
spec:
  schedule: "0 * * * *"  # This will run at the start of every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: log-cleaner
            image: log-cleaner:latest
            imagePullPolicy: IfNotPresent  # "Never" because we are using a local image
          restartPolicy: OnFailure
